/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Age: typeof import('./src/components/admin/Age.vue')['default']
    AgeDistribution: typeof import('./src/components/admin/AgeDistribution.vue')['default']
    AvatarUploader: typeof import('./src/components/user/AvatarUploader.vue')['default']
    ChangePasswordForm: typeof import('./src/components/user/ChangePasswordForm.vue')['default']
    EcgBackground: typeof import('./src/components/EcgBackground.vue')['default']
    EcgCanvasBg: typeof import('./src/components/EcgCanvasBg.vue')['default']
    EditDrawer: typeof import('./src/components/admin/EditDrawer.vue')['default']
    EditProfileForm: typeof import('./src/components/user/EditProfileForm.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButto: typeof import('element-plus/es')['ElButto']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRat: typeof import('element-plus/es')['ElRat']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileUploader: typeof import('./src/components/admin/FileUploader.vue')['default']
    GenderChart: typeof import('./src/components/admin/GenderChart.vue')['default']
    Pagination: typeof import('./src/components/admin/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scl90RadarChart: typeof import('./src/components/admin/Scl90RadarChart.vue')['default']
    SearchBar: typeof import('./src/components/admin/SearchBar.vue')['default']
    StudentOverview: typeof import('./src/components/admin/StudentOverview.vue')['default']
    StudentTable: typeof import('./src/components/admin/StudentTable.vue')['default']
    TestTrendChart: typeof import('./src/components/admin/TestTrendChart.vue')['default']
    UserInfoCard: typeof import('./src/components/user/UserInfoCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
