/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Age: typeof import('./src/components/admin/Age.vue')['default']
    AgeDistribution: typeof import('./src/components/admin/AgeDistribution.vue')['default']
    EcgBackground: typeof import('./src/components/EcgBackground.vue')['default']
    EcgCanvasBg: typeof import('./src/components/EcgCanvasBg.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButto: typeof import('element-plus/es')['ElButto']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    GenderChart: typeof import('./src/components/admin/GenderChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scl90RadarChart: typeof import('./src/components/admin/Scl90RadarChart.vue')['default']
    StudentOverview: typeof import('./src/components/admin/StudentOverview.vue')['default']
    TestTrendChart: typeof import('./src/components/admin/TestTrendChart.vue')['default']
  }
}
